-- Seed standard effort metadata from docs/2026_표준공수표_0522_v4.xlsx.
-- Source sheet: 표준공수, range A1:CN79. Project simulation columns are not seeded.

BEGIN;

WITH solution_seed (solution_code, solution_name, display_order) AS (
VALUES
  ('pbx', 'PBX', 10),
  ('sbc', 'SBC', 20),
  ('cti', 'CTI', 30),
  ('cms', 'CMS', 50),
  ('ivr', 'IVR', 60),
  ('oamp', 'OAMP', 80),
  ('callbot', 'CallBot', 90),
  ('stat', 'STAT', 100),
  ('wfm', 'WFM', 110)
)
INSERT INTO public.estimation_solution (
  solution_code,
  solution_name,
  display_order,
  active,
  created_at,
  updated_at,
  created_by,
  updated_by
)
SELECT
  solution_code,
  solution_name,
  display_order,
  true,
  now(),
  now(),
  NULL,
  NULL
FROM solution_seed
ON CONFLICT (solution_code)
DO UPDATE SET
  solution_name = EXCLUDED.solution_name,
  display_order = EXCLUDED.display_order,
  active = true,
  updated_at = now(),
  updated_by = NULL;

WITH variant_seed (
  solution_code,
  variant_code,
  variant_name,
  display_name,
  display_order
) AS (
VALUES
  ('pbx', 'avaya', 'Avaya', 'PBX', 10),
  ('sbc', 'default', 'Default', 'SBC', 20),
  ('cti', 'v5', 'v5', 'CTI v5', 30),
  ('cti', 'v4', 'v4', 'CTI v4', 40),
  ('cms', 'avaya', 'Avaya', 'CMS', 50),
  ('ivr', 'v3_1', '3.1', 'IVR 3.1', 60),
  ('ivr', 'ep', 'EP', 'IVR EP', 70),
  ('oamp', 'v3_5', '3.5', 'OAMP', 80),
  ('callbot', 'v3', '3', 'CallBot', 90),
  ('stat', 'v2', '2', 'STAT', 100),
  ('wfm', 'v4', '4', 'WFM', 110)
)
INSERT INTO public.estimation_solution_variant (
  solution_code,
  variant_code,
  variant_name,
  display_name,
  display_order,
  active,
  created_at,
  updated_at,
  created_by,
  updated_by
)
SELECT
  solution_code,
  variant_code,
  variant_name,
  display_name,
  display_order,
  true,
  now(),
  now(),
  NULL,
  NULL
FROM variant_seed
ON CONFLICT (solution_code, variant_code)
DO UPDATE SET
  variant_name = EXCLUDED.variant_name,
  display_name = EXCLUDED.display_name,
  display_order = EXCLUDED.display_order,
  active = true,
  updated_at = now(),
  updated_by = NULL;

WITH base_effort_seed (
  solution_code,
  variant_code,
  phase_code,
  phase_name,
  effort_mm,
  display_order
) AS (
VALUES
  ('pbx', 'avaya', 'analysis', '분석', 1, 10),
  ('pbx', 'avaya', 'design', '설계', 1, 20),
  ('pbx', 'avaya', 'implementation', '구현', 2, 30),
  ('pbx', 'avaya', 'test', '단위/통합테스트', 1, 40),
  ('pbx', 'avaya', 'deployment', '이행 및 모니터링', 1, 50),
  ('sbc', 'default', 'analysis', '분석', 0.5, 10),
  ('sbc', 'default', 'design', '설계', 0.5, 20),
  ('sbc', 'default', 'implementation', '구현', 1, 30),
  ('sbc', 'default', 'test', '단위/통합테스트', 0.5, 40),
  ('sbc', 'default', 'deployment', '이행 및 모니터링', 1, 50),
  ('cti', 'v5', 'analysis', '분석', 1, 10),
  ('cti', 'v5', 'design', '설계', 1, 20),
  ('cti', 'v5', 'implementation', '구현', 2, 30),
  ('cti', 'v5', 'test', '단위/통합테스트', 1, 40),
  ('cti', 'v5', 'deployment', '이행 및 모니터링', 1, 50),
  ('cti', 'v4', 'analysis', '분석', 0.25, 10),
  ('cti', 'v4', 'design', '설계', 0.25, 20),
  ('cti', 'v4', 'implementation', '구현', 0.5, 30),
  ('cti', 'v4', 'test', '단위/통합테스트', 0.5, 40),
  ('cti', 'v4', 'deployment', '이행 및 모니터링', 0.5, 50),
  ('cms', 'avaya', 'analysis', '분석', 0.25, 10),
  ('cms', 'avaya', 'design', '설계', 0.25, 20),
  ('cms', 'avaya', 'implementation', '구현', 2, 30),
  ('cms', 'avaya', 'test', '단위/통합테스트', 1, 40),
  ('cms', 'avaya', 'deployment', '이행 및 모니터링', 0.5, 50),
  ('ivr', 'v3_1', 'analysis', '분석', 0.5, 10),
  ('ivr', 'v3_1', 'design', '설계', 0.5, 20),
  ('ivr', 'v3_1', 'implementation', '구현', 3.5, 30),
  ('ivr', 'v3_1', 'test', '단위/통합테스트', 1, 40),
  ('ivr', 'v3_1', 'deployment', '이행 및 모니터링', 0.25, 50),
  ('ivr', 'ep', 'analysis', '분석', 0.5, 10),
  ('ivr', 'ep', 'design', '설계', 0.5, 20),
  ('ivr', 'ep', 'implementation', '구현', 3.5, 30),
  ('ivr', 'ep', 'test', '단위/통합테스트', 1, 40),
  ('ivr', 'ep', 'deployment', '이행 및 모니터링', 0.25, 50),
  ('oamp', 'v3_5', 'analysis', '분석', 0.25, 10),
  ('oamp', 'v3_5', 'design', '설계', 0.25, 20),
  ('oamp', 'v3_5', 'implementation', '구현', 1, 30),
  ('oamp', 'v3_5', 'test', '단위/통합테스트', 0.25, 40),
  ('oamp', 'v3_5', 'deployment', '이행 및 모니터링', 0.25, 50),
  ('callbot', 'v3', 'analysis', '분석', 1, 10),
  ('callbot', 'v3', 'design', '설계', 1, 20),
  ('callbot', 'v3', 'implementation', '구현', 9, 30),
  ('callbot', 'v3', 'test', '단위/통합테스트', 0.75, 40),
  ('callbot', 'v3', 'deployment', '이행 및 모니터링', 0.25, 50),
  ('stat', 'v2', 'analysis', '분석', 1.5, 10),
  ('stat', 'v2', 'design', '설계', 1.5, 20),
  ('stat', 'v2', 'implementation', '구현', 3, 30),
  ('stat', 'v2', 'test', '단위/통합테스트', 1, 40),
  ('stat', 'v2', 'deployment', '이행 및 모니터링', 1, 50),
  ('wfm', 'v4', 'analysis', '분석', 1.5, 10),
  ('wfm', 'v4', 'design', '설계', 1.5, 20),
  ('wfm', 'v4', 'implementation', '구현', 3, 30),
  ('wfm', 'v4', 'test', '단위/통합테스트', 1, 40),
  ('wfm', 'v4', 'deployment', '이행 및 모니터링', 1, 50)
)
INSERT INTO public.estimation_standard_base_effort_meta (
  solution_variant_id,
  phase_code,
  phase_name,
  effort_mm,
  display_order,
  active,
  created_at,
  updated_at,
  created_by,
  updated_by
)
SELECT
  variant.solution_variant_id,
  seed.phase_code,
  seed.phase_name,
  seed.effort_mm,
  seed.display_order,
  true,
  now(),
  now(),
  NULL,
  NULL
FROM base_effort_seed seed
JOIN public.estimation_solution_variant variant
  ON variant.solution_code = seed.solution_code
  AND variant.variant_code = seed.variant_code
ON CONFLICT (solution_variant_id, phase_code)
DO UPDATE SET
  phase_name = EXCLUDED.phase_name,
  effort_mm = EXCLUDED.effort_mm,
  display_order = EXCLUDED.display_order,
  active = true,
  updated_at = now(),
  updated_by = NULL;

WITH item_seed (
  excel_row_no,
  category_l1,
  category_l2,
  item_name,
  item_option,
  display_order
) AS (
VALUES
  (13, '공통정보', NULL, '업종', '금융_증권', 13),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 14),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 15),
  (16, '공통정보', NULL, '업종', '일반', 16),
  (17, '공통정보', NULL, '상담석수', '100 미만', 17),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 18),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 19),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 20),
  (21, '공통정보', NULL, '지점수', '10 미만', 21),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 22),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 23),
  (24, '공통정보', NULL, '지점수', '60 이상', 24),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 25),
  (26, '공통정보', NULL, '유형', '윈백', 26),
  (27, '공통정보', NULL, '유형', '신규', 27),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 28),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 29),
  (30, '개발/설치', NULL, '화면개발', NULL, 30),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 31),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 32),
  (33, '연동', NULL, '통신사', NULL, 33),
  (34, '연동', NULL, 'G450', '10 미만', 34),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 35),
  (36, '연동', NULL, 'G450', '20 이상', 36),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 37),
  (38, '연동', NULL, '상담 AP', NULL, 38),
  (39, '일반기능', NULL, 'PBX', NULL, 39),
  (40, '일반기능', NULL, 'CTI', NULL, 40),
  (41, '일반기능', NULL, 'IVR', NULL, 41),
  (42, '일반기능', NULL, '음성봇', NULL, 42),
  (43, '일반기능', NULL, 'PDS', NULL, 43),
  (44, '일반기능', NULL, 'STAT', NULL, 44),
  (45, '일반기능', NULL, '녹취', NULL, 45),
  (46, '일반기능', NULL, '통합관리', NULL, 46),
  (47, '일반기능', NULL, '관제', NULL, 47),
  (48, '일반기능', NULL, 'DB', NULL, 48),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 49),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 50),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 51),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 52),
  (53, '일반기능', NULL, 'TTS', NULL, 53),
  (54, '일반기능', NULL, 'STT', NULL, 54),
  (55, '일반기능', NULL, 'Push-XML', NULL, 55),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 56),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 57),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 58),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 59),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 60),
  (61, '일반기능', NULL, '모바일 화면', NULL, 61),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 62),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 63),
  (64, '추가 요구사항', NULL, '보안', NULL, 64),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 65),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 66),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 67),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 68),
  (69, 'WFM모듈', NULL, '공통', NULL, 69),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 70),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 71),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 72),
  (73, 'WFM모듈', NULL, '품질', NULL, 73),
  (74, 'WFM모듈', NULL, '성과', NULL, 74),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 75),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 76),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 77),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 78),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 79)
),
updated AS (
  UPDATE public.estimation_standard_item_meta target
  SET
    excel_row_no = seed.excel_row_no,
    display_order = seed.display_order,
    active = true,
    updated_at = now(),
    updated_by = NULL
  FROM item_seed seed
  WHERE target.category_l1 = seed.category_l1
    AND COALESCE(target.category_l2, '') = COALESCE(seed.category_l2, '')
    AND target.item_name = seed.item_name
    AND COALESCE(target.item_option, '') = COALESCE(seed.item_option, '')
  RETURNING target.item_id
)
INSERT INTO public.estimation_standard_item_meta (
  excel_row_no,
  category_l1,
  category_l2,
  item_name,
  item_option,
  display_order,
  active,
  created_at,
  updated_at,
  created_by,
  updated_by
)
SELECT
  seed.excel_row_no,
  seed.category_l1,
  seed.category_l2,
  seed.item_name,
  seed.item_option,
  seed.display_order,
  true,
  now(),
  now(),
  NULL,
  NULL
FROM item_seed seed
WHERE NOT EXISTS (
  SELECT 1
  FROM public.estimation_standard_item_meta target
  WHERE target.category_l1 = seed.category_l1
    AND COALESCE(target.category_l2, '') = COALESCE(seed.category_l2, '')
    AND target.item_name = seed.item_name
    AND COALESCE(target.item_option, '') = COALESCE(seed.item_option, '')
);

WITH coefficient_seed (
  excel_row_no,
  category_l1,
  category_l2,
  item_name,
  item_option,
  solution_code,
  variant_code,
  coefficient
) AS (
VALUES
  (13, '공통정보', NULL, '업종', '금융_증권', 'pbx', 'avaya', 0),
  (13, '공통정보', NULL, '업종', '금융_증권', 'sbc', 'default', 0),
  (13, '공통정보', NULL, '업종', '금융_증권', 'cti', 'v5', 0.2),
  (13, '공통정보', NULL, '업종', '금융_증권', 'cti', 'v4', 0),
  (13, '공통정보', NULL, '업종', '금융_증권', 'cms', 'avaya', 0),
  (13, '공통정보', NULL, '업종', '금융_증권', 'ivr', 'v3_1', 1.5),
  (13, '공통정보', NULL, '업종', '금융_증권', 'ivr', 'ep', 1.725),
  (13, '공통정보', NULL, '업종', '금융_증권', 'oamp', 'v3_5', 0),
  (13, '공통정보', NULL, '업종', '금융_증권', 'callbot', 'v3', 1),
  (13, '공통정보', NULL, '업종', '금융_증권', 'stat', 'v2', 0),
  (13, '공통정보', NULL, '업종', '금융_증권', 'wfm', 'v4', 0),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'pbx', 'avaya', 0),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'sbc', 'default', 0),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'cti', 'v5', 0.2),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'cti', 'v4', 0),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'cms', 'avaya', 0),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'ivr', 'v3_1', 1),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'ivr', 'ep', 1.15),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'oamp', 'v3_5', 0),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'callbot', 'v3', 0.5),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'stat', 'v2', 0),
  (14, '공통정보', NULL, '업종', '금융_증권 외', 'wfm', 'v4', 0),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'pbx', 'avaya', 0),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'sbc', 'default', 0),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'cti', 'v5', 0),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'cti', 'v4', 0),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'cms', 'avaya', 0),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'ivr', 'v3_1', 0.5),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'ivr', 'ep', 0.575),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'oamp', 'v3_5', 0),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'callbot', 'v3', 1),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'stat', 'v2', 0),
  (15, '공통정보', NULL, '업종', '홈쇼핑', 'wfm', 'v4', 0),
  (16, '공통정보', NULL, '업종', '일반', 'pbx', 'avaya', 0),
  (16, '공통정보', NULL, '업종', '일반', 'sbc', 'default', 0),
  (16, '공통정보', NULL, '업종', '일반', 'cti', 'v5', 0),
  (16, '공통정보', NULL, '업종', '일반', 'cti', 'v4', 0),
  (16, '공통정보', NULL, '업종', '일반', 'cms', 'avaya', 0),
  (16, '공통정보', NULL, '업종', '일반', 'ivr', 'v3_1', 0),
  (16, '공통정보', NULL, '업종', '일반', 'ivr', 'ep', 0),
  (16, '공통정보', NULL, '업종', '일반', 'oamp', 'v3_5', 0),
  (16, '공통정보', NULL, '업종', '일반', 'callbot', 'v3', 0),
  (16, '공통정보', NULL, '업종', '일반', 'stat', 'v2', 0),
  (16, '공통정보', NULL, '업종', '일반', 'wfm', 'v4', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'pbx', 'avaya', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'sbc', 'default', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'cti', 'v5', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'cti', 'v4', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'cms', 'avaya', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'ivr', 'v3_1', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'ivr', 'ep', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'oamp', 'v3_5', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'callbot', 'v3', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'stat', 'v2', 0),
  (17, '공통정보', NULL, '상담석수', '100 미만', 'wfm', 'v4', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'pbx', 'avaya', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'sbc', 'default', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'cti', 'v5', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'cti', 'v4', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'cms', 'avaya', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'ivr', 'v3_1', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'ivr', 'ep', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'oamp', 'v3_5', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'callbot', 'v3', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'stat', 'v2', 0),
  (18, '공통정보', NULL, '상담석수', '100 이상 500 미만', 'wfm', 'v4', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'pbx', 'avaya', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'sbc', 'default', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'cti', 'v5', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'cti', 'v4', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'cms', 'avaya', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'ivr', 'v3_1', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'ivr', 'ep', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'oamp', 'v3_5', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'callbot', 'v3', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'stat', 'v2', 0),
  (19, '공통정보', NULL, '상담석수', '500 이상 1000 미만', 'wfm', 'v4', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'pbx', 'avaya', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'sbc', 'default', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'cti', 'v5', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'cti', 'v4', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'cms', 'avaya', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'ivr', 'v3_1', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'ivr', 'ep', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'oamp', 'v3_5', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'callbot', 'v3', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'stat', 'v2', 0),
  (20, '공통정보', NULL, '상담석수', '1000 이상', 'wfm', 'v4', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'pbx', 'avaya', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'sbc', 'default', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'cti', 'v5', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'cti', 'v4', 0.25),
  (21, '공통정보', NULL, '지점수', '10 미만', 'cms', 'avaya', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'ivr', 'v3_1', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'ivr', 'ep', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'oamp', 'v3_5', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'callbot', 'v3', 0),
  (21, '공통정보', NULL, '지점수', '10 미만', 'stat', 'v2', 0.25),
  (21, '공통정보', NULL, '지점수', '10 미만', 'wfm', 'v4', 0),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'pbx', 'avaya', 0.8),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'sbc', 'default', 0.5),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'cti', 'v5', 0),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'cti', 'v4', 0.25),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'cms', 'avaya', 0),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'ivr', 'v3_1', 0),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'ivr', 'ep', 0),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'oamp', 'v3_5', 0),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'callbot', 'v3', 0),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'stat', 'v2', 0.25),
  (22, '공통정보', NULL, '지점수', '10 이상 40 미만', 'wfm', 'v4', 0),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'pbx', 'avaya', 1),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'sbc', 'default', 0.8),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'cti', 'v5', 0),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'cti', 'v4', 0.25),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'cms', 'avaya', 0),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'ivr', 'v3_1', 0),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'ivr', 'ep', 0),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'oamp', 'v3_5', 0),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'callbot', 'v3', 0),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'stat', 'v2', 0.25),
  (23, '공통정보', NULL, '지점수', '40 이상 60 미만', 'wfm', 'v4', 0),
  (24, '공통정보', NULL, '지점수', '60 이상', 'pbx', 'avaya', 1.5),
  (24, '공통정보', NULL, '지점수', '60 이상', 'sbc', 'default', 1),
  (24, '공통정보', NULL, '지점수', '60 이상', 'cti', 'v5', 0),
  (24, '공통정보', NULL, '지점수', '60 이상', 'cti', 'v4', 0.25),
  (24, '공통정보', NULL, '지점수', '60 이상', 'cms', 'avaya', 0),
  (24, '공통정보', NULL, '지점수', '60 이상', 'ivr', 'v3_1', 0),
  (24, '공통정보', NULL, '지점수', '60 이상', 'ivr', 'ep', 0),
  (24, '공통정보', NULL, '지점수', '60 이상', 'oamp', 'v3_5', 0),
  (24, '공통정보', NULL, '지점수', '60 이상', 'callbot', 'v3', 0),
  (24, '공통정보', NULL, '지점수', '60 이상', 'stat', 'v2', 0.25),
  (24, '공통정보', NULL, '지점수', '60 이상', 'wfm', 'v4', 0),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'pbx', 'avaya', 0.2),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'sbc', 'default', 0.5),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'cti', 'v5', 1),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'cti', 'v4', 1),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'cms', 'avaya', 0.4),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'ivr', 'v3_1', 0.1),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'ivr', 'ep', 0.115),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'oamp', 'v3_5', 0),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'callbot', 'v3', 0),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'stat', 'v2', 0),
  (25, '공통정보', NULL, '유형', '동일솔루션 고도화', 'wfm', 'v4', 1.25),
  (26, '공통정보', NULL, '유형', '윈백', 'pbx', 'avaya', 1),
  (26, '공통정보', NULL, '유형', '윈백', 'sbc', 'default', 1),
  (26, '공통정보', NULL, '유형', '윈백', 'cti', 'v5', 1),
  (26, '공통정보', NULL, '유형', '윈백', 'cti', 'v4', 1),
  (26, '공통정보', NULL, '유형', '윈백', 'cms', 'avaya', 1),
  (26, '공통정보', NULL, '유형', '윈백', 'ivr', 'v3_1', 1),
  (26, '공통정보', NULL, '유형', '윈백', 'ivr', 'ep', 1.15),
  (26, '공통정보', NULL, '유형', '윈백', 'oamp', 'v3_5', 0.25),
  (26, '공통정보', NULL, '유형', '윈백', 'callbot', 'v3', 0),
  (26, '공통정보', NULL, '유형', '윈백', 'stat', 'v2', 0),
  (26, '공통정보', NULL, '유형', '윈백', 'wfm', 'v4', 1),
  (27, '공통정보', NULL, '유형', '신규', 'pbx', 'avaya', 1),
  (27, '공통정보', NULL, '유형', '신규', 'sbc', 'default', 1),
  (27, '공통정보', NULL, '유형', '신규', 'cti', 'v5', 0),
  (27, '공통정보', NULL, '유형', '신규', 'cti', 'v4', 0),
  (27, '공통정보', NULL, '유형', '신규', 'cms', 'avaya', 0),
  (27, '공통정보', NULL, '유형', '신규', 'ivr', 'v3_1', 0),
  (27, '공통정보', NULL, '유형', '신규', 'ivr', 'ep', 0),
  (27, '공통정보', NULL, '유형', '신규', 'oamp', 'v3_5', 0),
  (27, '공통정보', NULL, '유형', '신규', 'callbot', 'v3', 0),
  (27, '공통정보', NULL, '유형', '신규', 'stat', 'v2', 0),
  (27, '공통정보', NULL, '유형', '신규', 'wfm', 'v4', 1),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'pbx', 'avaya', 0.1),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'sbc', 'default', 0),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'cti', 'v5', 0),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'cti', 'v4', 0),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'cms', 'avaya', 0),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'ivr', 'v3_1', 0.25),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'ivr', 'ep', 0.2875),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'oamp', 'v3_5', 0),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'callbot', 'v3', 0),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'stat', 'v2', 0),
  (28, '공통정보', NULL, 'DR센터 존재', NULL, 'wfm', 'v4', 0),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'pbx', 'avaya', 0),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'sbc', 'default', 0),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'cti', 'v5', 0),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'cti', 'v4', 0),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'cms', 'avaya', 0),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'ivr', 'v3_1', 0.25),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'ivr', 'ep', 0.2875),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'oamp', 'v3_5', 0),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'callbot', 'v3', 0.25),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'stat', 'v2', 0),
  (29, '개발/설치', NULL, '중계서버(HostClient기반)', NULL, 'wfm', 'v4', 0),
  (30, '개발/설치', NULL, '화면개발', NULL, 'pbx', 'avaya', 0),
  (30, '개발/설치', NULL, '화면개발', NULL, 'sbc', 'default', 0),
  (30, '개발/설치', NULL, '화면개발', NULL, 'cti', 'v5', 0),
  (30, '개발/설치', NULL, '화면개발', NULL, 'cti', 'v4', 0),
  (30, '개발/설치', NULL, '화면개발', NULL, 'cms', 'avaya', 0),
  (30, '개발/설치', NULL, '화면개발', NULL, 'ivr', 'v3_1', 0),
  (30, '개발/설치', NULL, '화면개발', NULL, 'ivr', 'ep', 0),
  (30, '개발/설치', NULL, '화면개발', NULL, 'oamp', 'v3_5', 0.5),
  (30, '개발/설치', NULL, '화면개발', NULL, 'callbot', 'v3', 0.1),
  (30, '개발/설치', NULL, '화면개발', NULL, 'stat', 'v2', 1),
  (30, '개발/설치', NULL, '화면개발', NULL, 'wfm', 'v4', 0),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'pbx', 'avaya', 0),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'sbc', 'default', 0),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'cti', 'v5', 0),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'cti', 'v4', 0),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'cms', 'avaya', 0),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'ivr', 'v3_1', 0.1),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'ivr', 'ep', 0.115),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'oamp', 'v3_5', 0),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'callbot', 'v3', 0.1),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'stat', 'v2', 0),
  (31, '개발/설치', NULL, '인증서비스 존재', NULL, 'wfm', 'v4', 0),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'pbx', 'avaya', 0),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'sbc', 'default', 0),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'cti', 'v5', 0),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'cti', 'v4', 0),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'cms', 'avaya', 0),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'ivr', 'v3_1', 0.1),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'ivr', 'ep', 0.115),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'oamp', 'v3_5', 0),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'callbot', 'v3', 0.1),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'stat', 'v2', 0.12),
  (32, '개발/설치', NULL, '콜백서비스 존재', NULL, 'wfm', 'v4', 0),
  (33, '연동', NULL, '통신사', NULL, 'pbx', 'avaya', 0),
  (33, '연동', NULL, '통신사', NULL, 'sbc', 'default', 0.12),
  (33, '연동', NULL, '통신사', NULL, 'cti', 'v5', 0),
  (33, '연동', NULL, '통신사', NULL, 'cti', 'v4', 0),
  (33, '연동', NULL, '통신사', NULL, 'cms', 'avaya', 0),
  (33, '연동', NULL, '통신사', NULL, 'ivr', 'v3_1', 0),
  (33, '연동', NULL, '통신사', NULL, 'ivr', 'ep', 0),
  (33, '연동', NULL, '통신사', NULL, 'oamp', 'v3_5', 0),
  (33, '연동', NULL, '통신사', NULL, 'callbot', 'v3', 0),
  (33, '연동', NULL, '통신사', NULL, 'stat', 'v2', 0),
  (33, '연동', NULL, '통신사', NULL, 'wfm', 'v4', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'pbx', 'avaya', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'sbc', 'default', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'cti', 'v5', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'cti', 'v4', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'cms', 'avaya', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'ivr', 'v3_1', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'ivr', 'ep', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'oamp', 'v3_5', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'callbot', 'v3', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'stat', 'v2', 0),
  (34, '연동', NULL, 'G450', '10 미만', 'wfm', 'v4', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'pbx', 'avaya', 0.05),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'sbc', 'default', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'cti', 'v5', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'cti', 'v4', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'cms', 'avaya', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'ivr', 'v3_1', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'ivr', 'ep', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'oamp', 'v3_5', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'callbot', 'v3', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'stat', 'v2', 0),
  (35, '연동', NULL, 'G450', '10 이상 20 미만', 'wfm', 'v4', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'pbx', 'avaya', 0.1),
  (36, '연동', NULL, 'G450', '20 이상', 'sbc', 'default', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'cti', 'v5', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'cti', 'v4', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'cms', 'avaya', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'ivr', 'v3_1', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'ivr', 'ep', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'oamp', 'v3_5', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'callbot', 'v3', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'stat', 'v2', 0),
  (36, '연동', NULL, 'G450', '20 이상', 'wfm', 'v4', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'pbx', 'avaya', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'sbc', 'default', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'cti', 'v5', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'cti', 'v4', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'cms', 'avaya', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'ivr', 'v3_1', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'ivr', 'ep', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'oamp', 'v3_5', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'callbot', 'v3', 0),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'stat', 'v2', 0.12),
  (37, '연동', NULL, '기간계/처리계/정보계', NULL, 'wfm', 'v4', 0.12),
  (38, '연동', NULL, '상담 AP', NULL, 'pbx', 'avaya', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'sbc', 'default', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'cti', 'v5', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'cti', 'v4', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'cms', 'avaya', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'ivr', 'v3_1', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'ivr', 'ep', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'oamp', 'v3_5', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'callbot', 'v3', 0),
  (38, '연동', NULL, '상담 AP', NULL, 'stat', 'v2', 0.12),
  (38, '연동', NULL, '상담 AP', NULL, 'wfm', 'v4', 0.12),
  (39, '일반기능', NULL, 'PBX', NULL, 'pbx', 'avaya', 0),
  (39, '일반기능', NULL, 'PBX', NULL, 'sbc', 'default', 0.15),
  (39, '일반기능', NULL, 'PBX', NULL, 'cti', 'v5', 1),
  (39, '일반기능', NULL, 'PBX', NULL, 'cti', 'v4', 1),
  (39, '일반기능', NULL, 'PBX', NULL, 'cms', 'avaya', 0),
  (39, '일반기능', NULL, 'PBX', NULL, 'ivr', 'v3_1', 0),
  (39, '일반기능', NULL, 'PBX', NULL, 'ivr', 'ep', 0),
  (39, '일반기능', NULL, 'PBX', NULL, 'oamp', 'v3_5', 0),
  (39, '일반기능', NULL, 'PBX', NULL, 'callbot', 'v3', 0.1),
  (39, '일반기능', NULL, 'PBX', NULL, 'stat', 'v2', 0.12),
  (39, '일반기능', NULL, 'PBX', NULL, 'wfm', 'v4', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'pbx', 'avaya', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'sbc', 'default', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'cti', 'v5', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'cti', 'v4', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'cms', 'avaya', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'ivr', 'v3_1', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'ivr', 'ep', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'oamp', 'v3_5', 0),
  (40, '일반기능', NULL, 'CTI', NULL, 'callbot', 'v3', 0.2),
  (40, '일반기능', NULL, 'CTI', NULL, 'stat', 'v2', 0.12),
  (40, '일반기능', NULL, 'CTI', NULL, 'wfm', 'v4', 0),
  (41, '일반기능', NULL, 'IVR', NULL, 'pbx', 'avaya', 0),
  (41, '일반기능', NULL, 'IVR', NULL, 'sbc', 'default', 0),
  (41, '일반기능', NULL, 'IVR', NULL, 'cti', 'v5', 1),
  (41, '일반기능', NULL, 'IVR', NULL, 'cti', 'v4', 1),
  (41, '일반기능', NULL, 'IVR', NULL, 'cms', 'avaya', 0),
  (41, '일반기능', NULL, 'IVR', NULL, 'ivr', 'v3_1', 0),
  (41, '일반기능', NULL, 'IVR', NULL, 'ivr', 'ep', 0),
  (41, '일반기능', NULL, 'IVR', NULL, 'oamp', 'v3_5', 0),
  (41, '일반기능', NULL, 'IVR', NULL, 'callbot', 'v3', 0),
  (41, '일반기능', NULL, 'IVR', NULL, 'stat', 'v2', 0.12),
  (41, '일반기능', NULL, 'IVR', NULL, 'wfm', 'v4', 0.12),
  (42, '일반기능', NULL, '음성봇', NULL, 'pbx', 'avaya', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'sbc', 'default', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'cti', 'v5', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'cti', 'v4', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'cms', 'avaya', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'ivr', 'v3_1', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'ivr', 'ep', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'oamp', 'v3_5', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'callbot', 'v3', 0),
  (42, '일반기능', NULL, '음성봇', NULL, 'stat', 'v2', 0.12),
  (42, '일반기능', NULL, '음성봇', NULL, 'wfm', 'v4', 0),
  (43, '일반기능', NULL, 'PDS', NULL, 'pbx', 'avaya', 0),
  (43, '일반기능', NULL, 'PDS', NULL, 'sbc', 'default', 0.12),
  (43, '일반기능', NULL, 'PDS', NULL, 'cti', 'v5', 0),
  (43, '일반기능', NULL, 'PDS', NULL, 'cti', 'v4', 0),
  (43, '일반기능', NULL, 'PDS', NULL, 'cms', 'avaya', 0),
  (43, '일반기능', NULL, 'PDS', NULL, 'ivr', 'v3_1', 0),
  (43, '일반기능', NULL, 'PDS', NULL, 'ivr', 'ep', 0),
  (43, '일반기능', NULL, 'PDS', NULL, 'oamp', 'v3_5', 0),
  (43, '일반기능', NULL, 'PDS', NULL, 'callbot', 'v3', 0.1),
  (43, '일반기능', NULL, 'PDS', NULL, 'stat', 'v2', 0.12),
  (43, '일반기능', NULL, 'PDS', NULL, 'wfm', 'v4', 0.12),
  (44, '일반기능', NULL, 'STAT', NULL, 'pbx', 'avaya', 0),
  (44, '일반기능', NULL, 'STAT', NULL, 'sbc', 'default', 0),
  (44, '일반기능', NULL, 'STAT', NULL, 'cti', 'v5', 0),
  (44, '일반기능', NULL, 'STAT', NULL, 'cti', 'v4', 0),
  (44, '일반기능', NULL, 'STAT', NULL, 'cms', 'avaya', 0.3),
  (44, '일반기능', NULL, 'STAT', NULL, 'ivr', 'v3_1', 0.5),
  (44, '일반기능', NULL, 'STAT', NULL, 'ivr', 'ep', 0.575),
  (44, '일반기능', NULL, 'STAT', NULL, 'oamp', 'v3_5', 0.25),
  (44, '일반기능', NULL, 'STAT', NULL, 'callbot', 'v3', 0),
  (44, '일반기능', NULL, 'STAT', NULL, 'stat', 'v2', 0),
  (44, '일반기능', NULL, 'STAT', NULL, 'wfm', 'v4', 0.12),
  (45, '일반기능', NULL, '녹취', NULL, 'pbx', 'avaya', 0),
  (45, '일반기능', NULL, '녹취', NULL, 'sbc', 'default', 0.12),
  (45, '일반기능', NULL, '녹취', NULL, 'cti', 'v5', 1),
  (45, '일반기능', NULL, '녹취', NULL, 'cti', 'v4', 1),
  (45, '일반기능', NULL, '녹취', NULL, 'cms', 'avaya', 0),
  (45, '일반기능', NULL, '녹취', NULL, 'ivr', 'v3_1', 0),
  (45, '일반기능', NULL, '녹취', NULL, 'ivr', 'ep', 0),
  (45, '일반기능', NULL, '녹취', NULL, 'oamp', 'v3_5', 0),
  (45, '일반기능', NULL, '녹취', NULL, 'callbot', 'v3', 0.1),
  (45, '일반기능', NULL, '녹취', NULL, 'stat', 'v2', 0.12),
  (45, '일반기능', NULL, '녹취', NULL, 'wfm', 'v4', 0.12),
  (46, '일반기능', NULL, '통합관리', NULL, 'pbx', 'avaya', 0.03),
  (46, '일반기능', NULL, '통합관리', NULL, 'sbc', 'default', 0),
  (46, '일반기능', NULL, '통합관리', NULL, 'cti', 'v5', 0.03),
  (46, '일반기능', NULL, '통합관리', NULL, 'cti', 'v4', 0.03),
  (46, '일반기능', NULL, '통합관리', NULL, 'cms', 'avaya', 0),
  (46, '일반기능', NULL, '통합관리', NULL, 'ivr', 'v3_1', 0),
  (46, '일반기능', NULL, '통합관리', NULL, 'ivr', 'ep', 0),
  (46, '일반기능', NULL, '통합관리', NULL, 'oamp', 'v3_5', 0),
  (46, '일반기능', NULL, '통합관리', NULL, 'callbot', 'v3', 0),
  (46, '일반기능', NULL, '통합관리', NULL, 'stat', 'v2', 0),
  (46, '일반기능', NULL, '통합관리', NULL, 'wfm', 'v4', 0),
  (47, '일반기능', NULL, '관제', NULL, 'pbx', 'avaya', 0.03),
  (47, '일반기능', NULL, '관제', NULL, 'sbc', 'default', 0),
  (47, '일반기능', NULL, '관제', NULL, 'cti', 'v5', 0.03),
  (47, '일반기능', NULL, '관제', NULL, 'cti', 'v4', 0.03),
  (47, '일반기능', NULL, '관제', NULL, 'cms', 'avaya', 0),
  (47, '일반기능', NULL, '관제', NULL, 'ivr', 'v3_1', 0),
  (47, '일반기능', NULL, '관제', NULL, 'ivr', 'ep', 0),
  (47, '일반기능', NULL, '관제', NULL, 'oamp', 'v3_5', 0),
  (47, '일반기능', NULL, '관제', NULL, 'callbot', 'v3', 0),
  (47, '일반기능', NULL, '관제', NULL, 'stat', 'v2', 0),
  (47, '일반기능', NULL, '관제', NULL, 'wfm', 'v4', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'pbx', 'avaya', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'sbc', 'default', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'cti', 'v5', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'cti', 'v4', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'cms', 'avaya', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'ivr', 'v3_1', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'ivr', 'ep', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'oamp', 'v3_5', 0.25),
  (48, '일반기능', NULL, 'DB', NULL, 'callbot', 'v3', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'stat', 'v2', 0),
  (48, '일반기능', NULL, 'DB', NULL, 'wfm', 'v4', 0),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'pbx', 'avaya', 0),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'sbc', 'default', 0.15),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'cti', 'v5', 0),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'cti', 'v4', 0),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'cms', 'avaya', 0),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'ivr', 'v3_1', 1),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'ivr', 'ep', 1.15),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'oamp', 'v3_5', 0),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'callbot', 'v3', 1),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'stat', 'v2', 0),
  (49, '일반기능', NULL, 'DTMF G/W(보이는ARS)', NULL, 'wfm', 'v4', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'pbx', 'avaya', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'sbc', 'default', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'cti', 'v5', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'cti', 'v4', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'cms', 'avaya', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'ivr', 'v3_1', 0.25),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'ivr', 'ep', 0.2875),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'oamp', 'v3_5', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'callbot', 'v3', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'stat', 'v2', 0),
  (50, '일반기능', NULL, 'Digital/말로하는 ARS', NULL, 'wfm', 'v4', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'pbx', 'avaya', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'sbc', 'default', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'cti', 'v5', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'cti', 'v4', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'cms', 'avaya', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'ivr', 'v3_1', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'ivr', 'ep', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'oamp', 'v3_5', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'callbot', 'v3', 0),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'stat', 'v2', 0.12),
  (51, '일반기능', NULL, '전광판', '3rd party 연동', 'wfm', 'v4', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'pbx', 'avaya', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'sbc', 'default', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'cti', 'v5', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'cti', 'v4', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'cms', 'avaya', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'ivr', 'v3_1', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'ivr', 'ep', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'oamp', 'v3_5', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'callbot', 'v3', 0),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'stat', 'v2', 0.25),
  (52, '일반기능', NULL, '전광판', 'ISAC 자사 개발', 'wfm', 'v4', 0.25),
  (53, '일반기능', NULL, 'TTS', NULL, 'pbx', 'avaya', 0),
  (53, '일반기능', NULL, 'TTS', NULL, 'sbc', 'default', 0),
  (53, '일반기능', NULL, 'TTS', NULL, 'cti', 'v5', 0),
  (53, '일반기능', NULL, 'TTS', NULL, 'cti', 'v4', 0),
  (53, '일반기능', NULL, 'TTS', NULL, 'cms', 'avaya', 0),
  (53, '일반기능', NULL, 'TTS', NULL, 'ivr', 'v3_1', 0.75),
  (53, '일반기능', NULL, 'TTS', NULL, 'ivr', 'ep', 0.8625),
  (53, '일반기능', NULL, 'TTS', NULL, 'oamp', 'v3_5', 0),
  (53, '일반기능', NULL, 'TTS', NULL, 'callbot', 'v3', 0.1),
  (53, '일반기능', NULL, 'TTS', NULL, 'stat', 'v2', 0),
  (53, '일반기능', NULL, 'TTS', NULL, 'wfm', 'v4', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'pbx', 'avaya', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'sbc', 'default', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'cti', 'v5', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'cti', 'v4', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'cms', 'avaya', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'ivr', 'v3_1', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'ivr', 'ep', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'oamp', 'v3_5', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'callbot', 'v3', 0.1),
  (54, '일반기능', NULL, 'STT', NULL, 'stat', 'v2', 0),
  (54, '일반기능', NULL, 'STT', NULL, 'wfm', 'v4', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'pbx', 'avaya', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'sbc', 'default', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'cti', 'v5', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'cti', 'v4', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'cms', 'avaya', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'ivr', 'v3_1', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'ivr', 'ep', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'oamp', 'v3_5', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'callbot', 'v3', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'stat', 'v2', 0),
  (55, '일반기능', NULL, 'Push-XML', NULL, 'wfm', 'v4', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'pbx', 'avaya', 0.1),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'sbc', 'default', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'cti', 'v5', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'cti', 'v4', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'cms', 'avaya', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'ivr', 'v3_1', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'ivr', 'ep', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'oamp', 'v3_5', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'callbot', 'v3', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'stat', 'v2', 0),
  (56, '일반기능', NULL, '교환기 스킬 라우팅', NULL, 'wfm', 'v4', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'pbx', 'avaya', 0.05),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'sbc', 'default', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'cti', 'v5', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'cti', 'v4', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'cms', 'avaya', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'ivr', 'v3_1', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'ivr', 'ep', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'oamp', 'v3_5', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'callbot', 'v3', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'stat', 'v2', 0),
  (57, '일반기능', NULL, '일반그룹 라우팅', NULL, 'wfm', 'v4', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'pbx', 'avaya', 0.05),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'sbc', 'default', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'cti', 'v5', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'cti', 'v4', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'cms', 'avaya', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'ivr', 'v3_1', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'ivr', 'ep', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'oamp', 'v3_5', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'callbot', 'v3', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'stat', 'v2', 0),
  (58, '일반기능', NULL, 'IVR멘트기능 수용', NULL, 'wfm', 'v4', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'pbx', 'avaya', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'sbc', 'default', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'cti', 'v5', 0.5),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'cti', 'v4', 1.5),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'cms', 'avaya', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'ivr', 'v3_1', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'ivr', 'ep', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'oamp', 'v3_5', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'callbot', 'v3', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'stat', 'v2', 0),
  (59, '일반기능', NULL, 'softphone 개발', NULL, 'wfm', 'v4', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'pbx', 'avaya', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'sbc', 'default', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'cti', 'v5', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'cti', 'v4', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'cms', 'avaya', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'ivr', 'v3_1', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'ivr', 'ep', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'oamp', 'v3_5', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'callbot', 'v3', 0),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'stat', 'v2', 0.12),
  (60, '일반기능', NULL, '모바일블래이드', NULL, 'wfm', 'v4', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'pbx', 'avaya', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'sbc', 'default', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'cti', 'v5', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'cti', 'v4', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'cms', 'avaya', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'ivr', 'v3_1', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'ivr', 'ep', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'oamp', 'v3_5', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'callbot', 'v3', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'stat', 'v2', 0),
  (61, '일반기능', NULL, '모바일 화면', NULL, 'wfm', 'v4', 0.25),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'pbx', 'avaya', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'sbc', 'default', 0.1),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'cti', 'v5', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'cti', 'v4', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'cms', 'avaya', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'ivr', 'v3_1', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'ivr', 'ep', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'oamp', 'v3_5', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'callbot', 'v3', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'stat', 'v2', 0),
  (62, '일반기능', NULL, '발신번호 서비스', 'ISAC-contact', 'wfm', 'v4', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'pbx', 'avaya', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'sbc', 'default', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'cti', 'v5', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'cti', 'v4', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'cms', 'avaya', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'ivr', 'v3_1', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'ivr', 'ep', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'oamp', 'v3_5', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'callbot', 'v3', 0),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'stat', 'v2', 0.12),
  (63, '일반기능', NULL, '기타(만족도조사,챗봇 등)', NULL, 'wfm', 'v4', 0.12),
  (64, '추가 요구사항', NULL, '보안', NULL, 'pbx', 'avaya', 0.25),
  (64, '추가 요구사항', NULL, '보안', NULL, 'sbc', 'default', 0),
  (64, '추가 요구사항', NULL, '보안', NULL, 'cti', 'v5', 0.25),
  (64, '추가 요구사항', NULL, '보안', NULL, 'cti', 'v4', 0.25),
  (64, '추가 요구사항', NULL, '보안', NULL, 'cms', 'avaya', 0.25),
  (64, '추가 요구사항', NULL, '보안', NULL, 'ivr', 'v3_1', 0.25),
  (64, '추가 요구사항', NULL, '보안', NULL, 'ivr', 'ep', 0.2875),
  (64, '추가 요구사항', NULL, '보안', NULL, 'oamp', 'v3_5', 0.25),
  (64, '추가 요구사항', NULL, '보안', NULL, 'callbot', 'v3', 0.25),
  (64, '추가 요구사항', NULL, '보안', NULL, 'stat', 'v2', 0.25),
  (64, '추가 요구사항', NULL, '보안', NULL, 'wfm', 'v4', 0.5),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'pbx', 'avaya', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'sbc', 'default', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'cti', 'v5', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'cti', 'v4', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'cms', 'avaya', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'ivr', 'v3_1', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'ivr', 'ep', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'oamp', 'v3_5', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'callbot', 'v3', 0),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'stat', 'v2', 0.12),
  (65, '추가 요구사항', NULL, 'DB Migration', NULL, 'wfm', 'v4', 0.12),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'pbx', 'avaya', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'sbc', 'default', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'cti', 'v5', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'cti', 'v4', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'cms', 'avaya', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'ivr', 'v3_1', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'ivr', 'ep', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'oamp', 'v3_5', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'callbot', 'v3', 0),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'stat', 'v2', 0.12),
  (66, '추가 요구사항', NULL, '통합 형상관리(별도구성)', NULL, 'wfm', 'v4', 0),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'pbx', 'avaya', 0),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'sbc', 'default', 0),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'cti', 'v5', 0),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'cti', 'v4', 0),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'cms', 'avaya', 0),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'ivr', 'v3_1', 0.3),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'ivr', 'ep', 0.345),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'oamp', 'v3_5', 0.25),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'callbot', 'v3', 0),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'stat', 'v2', 0.06),
  (67, '추가 요구사항', NULL, '감리대응', NULL, 'wfm', 'v4', 0.5),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'pbx', 'avaya', 0.5),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'sbc', 'default', 0.5),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'cti', 'v5', 0.06),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'cti', 'v4', 0.06),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'cms', 'avaya', 0.06),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'ivr', 'v3_1', 0.06),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'ivr', 'ep', 0.06),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'oamp', 'v3_5', 0.06),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'callbot', 'v3', 0.06),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'stat', 'v2', 0.06),
  (68, '추가 요구사항', NULL, '시스템 이전', NULL, 'wfm', 'v4', 0.06),
  (69, 'WFM모듈', NULL, '공통', NULL, 'pbx', 'avaya', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'sbc', 'default', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'cti', 'v5', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'cti', 'v4', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'cms', 'avaya', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'ivr', 'v3_1', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'ivr', 'ep', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'oamp', 'v3_5', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'callbot', 'v3', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'stat', 'v2', 0),
  (69, 'WFM모듈', NULL, '공통', NULL, 'wfm', 'v4', 1),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'pbx', 'avaya', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'sbc', 'default', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'cti', 'v5', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'cti', 'v4', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'cms', 'avaya', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'ivr', 'v3_1', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'ivr', 'ep', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'oamp', 'v3_5', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'callbot', 'v3', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'stat', 'v2', 0),
  (70, 'WFM모듈', NULL, '예측/트래킹', NULL, 'wfm', 'v4', 1),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'pbx', 'avaya', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'sbc', 'default', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'cti', 'v5', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'cti', 'v4', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'cms', 'avaya', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'ivr', 'v3_1', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'ivr', 'ep', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'oamp', 'v3_5', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'callbot', 'v3', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'stat', 'v2', 0),
  (71, 'WFM모듈', NULL, '스케줄/근태', NULL, 'wfm', 'v4', 1),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'pbx', 'avaya', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'sbc', 'default', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'cti', 'v5', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'cti', 'v4', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'cms', 'avaya', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'ivr', 'v3_1', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'ivr', 'ep', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'oamp', 'v3_5', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'callbot', 'v3', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'stat', 'v2', 0),
  (72, 'WFM모듈', NULL, '인사/배치', NULL, 'wfm', 'v4', 0.5),
  (73, 'WFM모듈', NULL, '품질', NULL, 'pbx', 'avaya', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'sbc', 'default', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'cti', 'v5', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'cti', 'v4', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'cms', 'avaya', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'ivr', 'v3_1', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'ivr', 'ep', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'oamp', 'v3_5', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'callbot', 'v3', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'stat', 'v2', 0),
  (73, 'WFM모듈', NULL, '품질', NULL, 'wfm', 'v4', 1),
  (74, 'WFM모듈', NULL, '성과', NULL, 'pbx', 'avaya', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'sbc', 'default', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'cti', 'v5', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'cti', 'v4', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'cms', 'avaya', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'ivr', 'v3_1', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'ivr', 'ep', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'oamp', 'v3_5', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'callbot', 'v3', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'stat', 'v2', 0),
  (74, 'WFM모듈', NULL, '성과', NULL, 'wfm', 'v4', 0.9),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'pbx', 'avaya', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'sbc', 'default', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'cti', 'v5', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'cti', 'v4', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'cms', 'avaya', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'ivr', 'v3_1', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'ivr', 'ep', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'oamp', 'v3_5', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'callbot', 'v3', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'stat', 'v2', 0),
  (75, 'WFM모듈', NULL, '교육/시험/설문', NULL, 'wfm', 'v4', 0.5),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'pbx', 'avaya', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'sbc', 'default', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'cti', 'v5', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'cti', 'v4', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'cms', 'avaya', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'ivr', 'v3_1', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'ivr', 'ep', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'oamp', 'v3_5', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'callbot', 'v3', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'stat', 'v2', 0),
  (76, 'WFM모듈', NULL, '통계/보고서', '1~40본', 'wfm', 'v4', 1),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'pbx', 'avaya', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'sbc', 'default', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'cti', 'v5', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'cti', 'v4', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'cms', 'avaya', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'ivr', 'v3_1', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'ivr', 'ep', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'oamp', 'v3_5', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'callbot', 'v3', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'stat', 'v2', 0),
  (77, 'WFM모듈', NULL, '통계/보고서', '41~80본', 'wfm', 'v4', 1.9),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'pbx', 'avaya', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'sbc', 'default', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'cti', 'v5', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'cti', 'v4', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'cms', 'avaya', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'ivr', 'v3_1', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'ivr', 'ep', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'oamp', 'v3_5', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'callbot', 'v3', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'stat', 'v2', 0),
  (78, 'WFM모듈', NULL, '통계/보고서', '81~120본', 'wfm', 'v4', 2.8),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'pbx', 'avaya', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'sbc', 'default', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'cti', 'v5', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'cti', 'v4', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'cms', 'avaya', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'ivr', 'v3_1', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'ivr', 'ep', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'oamp', 'v3_5', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'callbot', 'v3', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'stat', 'v2', 0),
  (79, 'WFM모듈', NULL, '통계/보고서', '120본 이상', 'wfm', 'v4', 3.7)
)
INSERT INTO public.estimation_item_solution_coefficient_meta (
  item_id,
  solution_variant_id,
  coefficient,
  active,
  created_at,
  updated_at,
  created_by,
  updated_by
)
SELECT
  item.item_id,
  variant.solution_variant_id,
  seed.coefficient,
  true,
  now(),
  now(),
  NULL,
  NULL
FROM coefficient_seed seed
JOIN public.estimation_standard_item_meta item
  ON item.category_l1 = seed.category_l1
  AND COALESCE(item.category_l2, '') = COALESCE(seed.category_l2, '')
  AND item.item_name = seed.item_name
  AND COALESCE(item.item_option, '') = COALESCE(seed.item_option, '')
JOIN public.estimation_solution_variant variant
  ON variant.solution_code = seed.solution_code
  AND variant.variant_code = seed.variant_code
ON CONFLICT (item_id, solution_variant_id)
DO UPDATE SET
  coefficient = EXCLUDED.coefficient,
  active = true,
  updated_at = now(),
  updated_by = NULL;

COMMIT;
